# Generated by Django 2.0 on 2019-05-03 14:34

from django.db import migrations, models


def forward(apps, schema_editor):
  Photo = apps.get_model('photologue', 'Photo')
  for photo in Photo.objects.all():
      photo.image_path = str(photo.image.file)
      photo.save()


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0011_auto_20190223_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_path',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.RunPython(forward),
        migrations.RemoveField(
            model_name='photo',
            name='image',
        ),
    ]
