# Generated by Django 2.1.5 on 2019-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0012_auto_20190503_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(max_length=250, verbose_name='title'),
        ),
    ]
