# Generated by Django 2.1.5 on 2019-05-09 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0014_gallery_complete_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_path',
            field=models.CharField(max_length=700),
        ),
    ]
