# Generated by Django 2.1.5 on 2019-05-27 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0015_auto_20190509_0600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photopath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
            ],
        ),
    ]
