# Generated by Django 2.1.5 on 2019-05-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photologue', '0016_photopath'),
    ]

    operations = [
        migrations.AddField(
            model_name='photopath',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
